language: go

go:
  - 1.13.x

# use the latest ubuntu environment (18.04) available on travis
dist: bionic

##install packages, before running scripts
before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

# script
script:
  - go test ./... -v