language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.14.x

# use the latest ubuntu environment (18.04) available on travis
dist: bionic

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# install packages, before running scripts
before_install:
  - go get github.com/mattn/goveralls

# script
script:
  - gotest -v ./...